//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Group
    {
        public Group()
        {
            this.Description = "";
            this.GroupMembers = new ObservableCollection<GroupMember>();
            this.Scheduledetails = new ObservableCollection<Scheduledetail>();
        }
    
        public int Group_Ref { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
    
        public virtual ObservableCollection<GroupMember> GroupMembers { get; set; }
        public virtual ObservableCollection<Scheduledetail> Scheduledetails { get; set; }
    }
}
