//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.StartTime = 0;
            this.EndTime = 0;
            this.Scheduledetails = new ObservableCollection<Scheduledetail>();
        }
    
        public int Schedule_Ref { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public bool Accepted { get; set; }
        public int Site_Ref { get; set; }
    
        public virtual ObservableCollection<Scheduledetail> Scheduledetails { get; set; }
        public virtual Site Site { get; set; }
    }
}
