//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Site
    {
        public Site()
        {
            this.Name = "";
            this.Address = "";
            this.City = "";
            this.Phone = "";
            this.SiteMembers = new ObservableCollection<SiteMember>();
            this.Schedules = new ObservableCollection<Schedule>();
            this.Works = new ObservableCollection<Work>();
        }
    
        public int Site_Ref { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
    
        public virtual ObservableCollection<SiteMember> SiteMembers { get; set; }
        public virtual ObservableCollection<Schedule> Schedules { get; set; }
        public virtual ObservableCollection<Work> Works { get; set; }
    }
}
