//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class SiteMember
    {
        public SiteMember()
        {
            this.Site_Ref = 0;
            this.User_Ref = 0;
        }
    
        public int SiteMember_Ref { get; set; }
        public int Site_Ref { get; set; }
        public int User_Ref { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual User User { get; set; }
    }
}
